[package]
name = "scribe"
version = "0.1.0"
authors = ["Brandon Waite"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"crossterm" = "*"
