[package]
name = "scribe"
version = "0.0.3-preview"
authors = ["Brandon Waite"]
edition = "2018"

[dependencies]
termion = "1.5.5"
libc = "0.2.69"
log = { version = "0.4.8", features = ["std"] }
dirs = "2.0.2"
rusqlite = { version = "0.23.1", features = ["bundled"] }
base64 = "0.11.0"